mod.id = "autogg"
mod.name = "AutoGG"
mod.group = "club.sk1er.mods"
mod.version = "4.1.3"

deps.fabric_loader = "0.19.5"
loomx.loom_version = "1.17-SNAPSHOT"

["26.1"]
mod.mc_compat = "~26.1"
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]

deps.fabric_api = "0.155.3+26.1.2"

["26.2"]
mod.mc_compat = "26.2"
mod.mc_releases = ["26.2"]

deps.fabric_api = "0.161.0+26.2"

["26.3"]
mod.mc_compat = "26.3"
mod.mc_releases = ["26.3"]

deps.fabric_api = "0.162.0+26.3"
